version: '2'
services:
  inspircd:
    image: inspircd/inspircd-docker
    volumes:
      - "./inspircd.conf:/inspircd/conf.d/links.conf"
    #environment:
    # - "INSP_SERVICES_PASSWORD=password"
    # - "INSP_SERVICES_NAME=services.example.com"
    ports:
      - "6667:6667"
      - "6697:6697"
  services:
    image: anope:testing
    build: 
      context: ..
      args:
       - "VERSION=2.0.5"
    environment:
      - "ANOPE_SERVICES_NAME=services.example.com"
      - "ANOPE_UPLINK_IP=inspircd"
      - "ANOPE_UPLINK_PASSWORD=password"
      # comment the lines below to use sqlite instead
      - "ANOPE_SQL_ENGINE=mysql"
      - "ANOPE_MYSQL_PASSWORD=anope"
    depends_on:
      - inspircd
      - database
  database:
    image: mariadb:10.1
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_USER=anope"
      - "MYSQL_PASSWORD=anope"
      - "MYSQL_DATABASE=anope"

